### PR TITLE
Fix sql injection vulnerability in Getting Started example

### PR DESCRIPTION
**Pull request by djfurman**
*Issue #, if available:* N/A

*Description of changes:*

- Fix SQL injection vulnerability in Python code sample query construction
- Type indicated python example code. 
- Provide inline code style indications to all instances. 
- Fix JSON structure examples to follow correct indentation.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by ellkend-aws** [comment]
@djfurman Thank you for submitting a PR and for letting us know about SQL injection vulnerability. We'll get this fixed in the doc source and update GitHub accordingly. Unfortunately, the syntax highlighting in your PR won't persist due to how we generate the markdown files. For now, I'll close your PR. I'll provide an update where when the fix is complete.

**Comment by djfurman** [comment]
Oh shoot. Sorry I didn't realize the declarations would cause a problem. Happy to revise if that's easier. 

Thanks for the quick response. Let me know how I can assist!

**Comment by ellkend-aws** [comment]
@djfurman Just letting you know that your suggestions have been incorporated into the guide. Right now, we don't support syntax highlighting for code samples in our markdown pages. Thanks again for your feedback and for using Amazon EMR.

**Comment by djfurman** [comment]
Thank you!

**Pull request closed without merging**
